version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "10:00"
      timezone: "Europe/Warsaw"
    rebase-strategy: "auto"
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - "cargo"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    labels:
      - "actions"
      - "dependencies"
